### ISSUE TITLE
Wrong form values on pop state

### ISSUE THREAD

**Issue by thelucid** [defunkt/jquery-pjax#482] opened 2015-02-09 00:58 UTC
When using browser back/forward buttons after a pjax submit, the form values don't revert. This is especially problematic with get requests as the form elements are then out of sync with the query params.

**Comment by arancedisicilia** [comment] 2015-03-03 18:39
I have the same exact problem.
I found a workaround by changing line 455,
from:
      var direction, contents = cacheMapping[state.id]
to:
      var direction, contents = cacheMapping[previousState.id]

This solves, but I didn't test enough for side effects.

**Comment by mislav** [comment] 2015-03-03 20:17
If you temporarily disable pjax for this form and use the back button after submitting the form, do the form values revert?

**Comment by arancedisicilia** [comment] 2015-03-03 23:47
They do revert when pjax is disabled.

I also noticed the following (with pjax on).

My form has a text input and 2 sets of checkboxes. Whenever I change any of the form values, the form is submitted.
If I submit N times, then going back will cause that:

- submit results are updated correctly
- form state is always one step ahead of results

**Comment by mislav** [comment] 2015-04-02 14:40
Could everyone try the 1.9.6 release and see if it fixes the problem on popstate? There was some fixes about how we maintain container and cache information between states. Thanks.

**Comment by stereosteve** [comment] 2016-05-18 14:39
I encounterd a similar issue and think I understand the cause.

Example:

1. I have an unchecked checkbox with an event listener.
2. When I check the box, I build a new URL and call PJAX.
3. Now I see new contents that correspond with the "checked" state.
4. If I press back, I'll see the "unchecked" contents but the checkbox will be checked.

The reason is the internal PJAX cache takes a snapshot of the "unchecked" page after the checkbox is checked but before the contents are updated (i.e. in step 2)

The quick fix for this is to disable the cache:

```
$.pjax.defaults.maxCacheLength = 0
```

Pressing back now results in a request to the server... You loose the super fast "back" behavior, but it does simplify things.

**Comment by stereosteve** [comment] 2016-06-16 21:49
@mislav -

I suspect that setting `$.pjax.defaults.maxCacheLength = 0` on github.com would fix an ongoing issue on github:

* Add a comment to an issue that contains a link
* Click the link to visit a different page
* Navigate back to issue... your comment is missing!
* When you reload the page your comment appears

I think the pjax cache is to blame.

**Comment by omzy** [comment] 2019-03-26 11:42
I am having problems with this as well. I have set `maxCacheLength` to `0` but my checkbox state isn't updating when I click back.

I can see in the DOM the checkbox loses the `checked` attribute, however it still remains visually checked. I'm not using any checkbox styling, it's just the bog standard checkbox. Issue occurs in both Chrome and Firefox.

**Closed** 2021-10-04 09:34 UTC
Labels: unconfirmed
