### ISSUE TITLE
jquery-pjax is not compatible with jQuery 3.0.0

### ISSUE THREAD

**Issue by WTVader** [defunkt/jquery-pjax#634] opened 2016-06-19 21:32 UTC
When using the latest version of jquery (3.0.0) jQuery.event.props is undefined in pjax. See also https://github.com/jquery/api.jquery.com/issues/405

**Comment by semiromid** [comment] 2016-06-20 08:02
I also

**Comment by juanmendez92** [comment] 2016-06-25 16:12
It's true, I have the same problem with jQuery 3.0.0

**Comment by celsworth** [comment] 2016-07-04 12:08
Looks like `$.event.props` was removed: https://jquery.com/upgrade-guide/3.0/#breaking-change-jquery-event-props-and-jquery-event-fixhooks-removed

**Comment by oh-ren** [comment] 2016-07-04 14:59
https://github.com/defunkt/jquery-pjax/blob/master/jquery.pjax.js#L914

````js
if ( $.event.props && $.inArray('state', $.event.props) < 0 ) {
  $.event.props.push('state');
} else if ( ! ('state' in $.Event.prototype) ) {
  $.event.addProp('state');
}
```

**Comment by itwy** [comment] 2016-07-05 18:42
@oh-ren waiting for the remaining fixes :)

**Comment by oh-ren** [comment] 2016-07-06 16:43
Ok, I fabricated something.
Use at your own peril though (just came up with this, but things seem to work) ;-)

https://gist.github.com/oh-ren/7afed121c2cd29993bd26c996fc6f501

**Comment by itwy** [comment] 2016-07-06 17:22
Thank you so much @oh-ren, it works fine for me.

**Comment by WTVader** [comment] 2016-07-10 06:57
Good job oh-ren! Your modification works also fine for me. However, a major rework of pjax might be a good approach for the future.

**Comment by oh-ren** [comment] 2016-07-10 08:37
Thanks guys, I just made an issue (#638) regarding the future / maintenance status of the plugin.

**Comment by itwy** [comment] 2016-07-16 17:13
Unfortunately, in some instances, the fix does not replace the page content. Not sure why though but reverting to the jq 2 works as expected. No error messages :(

**Comment by oh-ren** [comment] 2016-07-16 22:09
Hmm... Not run into that yet myself (but not using it *that* intensively).
Let me/us know if you get an idea perhaps what might be the cause..
Is just reverting back to jQ2 sufficient, or do you also need to revert back to the original pjax?

**Comment by itwy** [comment] 2016-07-16 23:01
> Is just reverting back to jQ2 sufficient, or do you also need to revert back to the original pjax?
I switched both and it worked. No idea which anymore to be honest. 

> (ps. what browser or you testing/running on?)
Latest Chrome/Mac 

> do you recall if it perhaps only seems to happen when navigation through the browers's history vs. navigating via page links?
I happened when I clicked.

I actually wrestled with the issue for a few hours today until I gave up on pjax altogether and switched to Turbolinks. I suddenly felt I am wasting my time with an abandonware. Nonetheless, I greatly appreciate your help.

**Comment by oh-ren** [comment] 2016-07-17 09:00
> I actually wrestled with the issue for a few hours today until I gave up on pjax altogether and switched to Turbolinks. I suddenly felt I am wasting my time with an abandonware. Nonetheless, I greatly appreciate your help.

Seems you are right..! Will check out [Turbolinks](https://github.com/turbolinks/turbolinks) myself (why haven't I heard of it before?) It seems it stems from the Rails world, am I right?

I did once, I guess when looking for pjax alternatives, stumble upon [Intercooler](http://intercoolerjs.org), but for some reason didn't seem to come across Turbolinks.. Have you checked the former out as well perhaps?

Anyway, thanks for mentioning!

**Comment by itwy** [comment] 2016-07-17 16:57
> It seems it stems from the Rails world, am I right?

Yes, it was build by the small team at basecamp.com to avoid maintaining two codebases. It's nice to use it with Rails, it's not mandatory, I am using it with Django now and all I had to do is to write some JS and backend initialization to handle form submissions.

Also, Turbolinks comes official Android and iOS wrappers: https://www.youtube.com/watch?v=SWEts0rlezA

I haven't checked Intercooler but it looks like it requires writing an Intercooler applications with no option of removing it without severe refactoring which is not how pjax and Turbolinks are built.

**Comment by WTVader** [comment] 2016-07-22 21:47
I spent some hours to setup Turbolinks for my needs, but gave up after a while since Turbolinks replaces the current <body> element rather than a designated container. So I'll stick to pjax and hope I major rework will be available sooner or later.

**Comment by markdavies** [comment] 2016-08-10 05:14
I was initially put off by Turbolinks replacing the entire body. You can actually specify elements that are "permanent" though with the `data-turbolinks-permanent` parameter. Seems to be working well, so I'm moving over.

**Comment by WTVader** [comment] 2016-08-10 05:33
Well, but still the entire body element will be replaced with some exceptions. Not a feasible approach for my point of view. It's much better to select what should be replaced with an ajax call.

**Comment by itwy** [comment] 2016-08-10 15:19
> Turbolinks replaces the current body element rather than a designated container.

I am loading these bits via some simple generic AJAX code. Definitely not doing a full reload when submitting forms, etc.

**Comment by mislav** [comment] 2016-09-08 10:41
@oh-ren Could you submit a pull request that restores jQ 3 compatibility?

**Comment by oh-ren** [comment] 2016-09-10 10:28
@mislav I consider my [gist](https://gist.github.com/oh-ren/7afed121c2cd29993bd26c996fc6f501) more or less a quick & dirty fix/workaround, so I didn't submit it as a PR on purpose.. Of course I still can do so if you want me to, I guess it would make it easy to review that way anyway right?

**Comment by mislav** [comment] 2016-09-10 14:53
Benefits of a PR is that I can see a diff online, comment on it, and when merged, it records you as a contributor in git history.

**Comment by pencilcheck** [comment] 2016-10-25 20:43
Looks like jquery-rails allows to include jquery2 specifically by changing from `//= require jquery` to `//= require jquery2`

**Comment by tm1000** [comment] 2016-10-28 23:58
Another way to make this work with jquery 3.0 is to use jquery migrate: https://code.jquery.com/jquery-migrate-3.0.0.js

**Comment by lydell** [comment] 2016-11-08 09:44
> Another way to make this work with jquery 3.0 is to use jquery migrate

Except that the back and forward buttons won’t work unless you add an extra script: https://github.com/defunkt/jquery-pjax/issues/638#issuecomment-259090560

**Closed** 2017-05-19 18:26 UTC

**Comment by mislav** [comment] 2017-05-19 18:47
jquery-pjax now works with jQuery versions 1.12 to 3.2: https://github.com/defunkt/jquery-pjax/releases/tag/v2.0.0

**Comment by lydell** [comment] 2017-05-20 10:04
@mislav Thanks! I upgraded to jquery-pjax 2.0.0 in my jQuery 3 project and removed jquery-migrate and everything seems to work! 🎉
