### ISSUE TITLE
Pjax is disabled on iOS 10

### ISSUE THREAD

**Issue by piotrgrzegorczyksii** [defunkt/jquery-pjax#472] opened 2015-01-13 18:21 UTC
Could you please update your code
<code>
// pushState isn't reliable on iOS until 5.
!navigator.userAgent.match(/((iPod|iPhone|iPad).+\bOS\s+[1-4]|WebApps\/.+CFNetwork)/)
</code>
to enable pjax on iOS 10.
iOS 10 pass regex test <b>OS\s+[1-4]</b>

**Comment by staabm** [comment] 2015-01-13 18:40
Duplicate of https://github.com/defunkt/jquery-pjax/issues/443 ?

**Comment by mislav** [comment] 2015-01-13 19:57
Yes, this was fixed in 863b802a84af8a9c72def4984d4d38163541fe6d and released since then.

**Closed by mislav** 2015-01-13 19:57 UTC
